---
# Install Nagios and related

- name: Add Nagios group
  group: name=nagcmd state=present gid=1337

- name: Add Nagios user
  user:
      name=nagios
      password='$6$saltsalt$LENhUpo6Ui46lgQoMdVh8jyDdoXhlq.TF1B8sKQgmQbr6FzsovxV5Y0VZgGgBQyZm08itfdbLggEjocuAgdoQ/'
      state=present
      groups=nagcmd
      comment="Nagios sys user"

- name: Apache user to Nagios group
  user:
      name=apache
      state=present
      groups=nagcmd

- name: Create directory where to compile
  file: path={{ nagtmp }} state=directory

- name: upload & extract files
  unarchive: src=roles/nagios/files/nagios-4.2.1.tar.gz dest={{ nagtmp }}

- name: upload & extract nagios plugins
  unarchive: src=roles/nagios/files/nagios-plugins-2.1.3.tar.gz dest={{ nagtmp }}

- name: upload & extract NRPE
  unarchive: src=roles/nagios/files/nrpe-2.15.tar.gz dest={{ nagtmp }}

- name: upload & extract nagios logfiles plugin
  unarchive: src=roles/nagios/files/check_logfiles-3.7.6.3.tar.gz dest={{ nagtmp }}

- name: Run ./configure for Nagios
  shell: cd {{ nagtmp }}/{{ nagiossrc }} && ./configure --with-command-group=nagcmd creates={{ nagtmp }}/{{ nagiossrc }}/Makefile

- name: Make all
  shell: cd {{ nagtmp }}/{{ nagiossrc }} && make all creates={{ nagtmp }}/{{ nagiossrc }}/base/nagios

- name: Make install
  shell: cd {{ nagtmp }}/{{ nagiossrc }} && make install creates=/usr/local/nagios/bin/nagios

- name: Make install-config
  shell: cd {{ nagtmp }}/{{ nagiossrc }} && make install-config creates=/usr/local/nagios/etc/nagios.cfg 

- name: Make install-commandmode
  shell: cd {{ nagtmp }}/{{ nagiossrc }} && make install-commandmode creates=/usr/local/nagios/var/rw

- name: Make install-devel
  shell: cd {{ nagtmp }}/{{ nagiossrc }} && make install-devel creates=/usr/local/nagios/include/nagios/nagios.h

- name: Make install-webconf
  shell: cd {{ nagtmp }}/{{ nagiossrc }} && make install-webconf creates=/etc/httpd/conf.d/nagios.conf

- name: Make install-init
  shell: cd {{ nagtmp }}/{{ nagiossrc }} && make install-init creates=/etc/init.d/nagios
  notify: restart apache

- name: Set password for nagiosadmin
  htpasswd: path=/usr/local/nagios/etc/htpasswd.users name=nagiosadmin password={{ nagiosadminpass }} state=present

- name: Configure Nagios Plugins
  shell: cd {{ nagtmp }}/{{ pluginssrc }} && ./configure --with-nagios-user=nagios --with-nagios-group=nagios --with-openssl=/usr/bin/openssl creates={{ nagtmp }}/{{ pluginssrc }}/Makefile

- name: Make Plugins
  shell: cd {{ nagtmp }}/{{ pluginssrc }} && make creates={{ nagtmp }}/{{ pluginssrc }}/plugins/check_ping

- name: Make Install Plugins
  shell: cd {{ nagtmp }}/{{ pluginssrc }} && make install creates=/usr/local/nagios/libexec/check_ping

- name: Configure NRPE
  shell: cd {{ nagtmp }}/{{ nrpesrc }} && ./configure --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu creates={{ nagtmp }}/{{ nrpesrc }}/Makefile

- name: Make NRPE
  shell: cd {{ nagtmp }}/{{ nrpesrc }} && make all creates={{ nagtmp }}/{{ nrpesrc }}/src/check_nrpe

- name: Copy check_nrpe
  shell: cp {{ nagtmp }}/{{ nrpesrc }}/src/check_nrpe /usr/local/nagios/libexec/check_nrpe creates=/usr/local/nagios/libexec/check_nrpe

- name: Copy nrpe daemon
  shell: cp {{ nagtmp }}/{{ nrpesrc }}/src/nrpe /usr/local/nagios/bin/nrpe creates=/usr/local/nagios/bin/nrpe

- name: Configure Check logfiles plugin
  shell: cd {{ nagtmp }}/{{ checklogs }} && ./configure creates={{ nagtmp }}/{{ checklogs }}/Makefile

- name: make check logfiles plugin
  shell: cd {{ nagtmp }}/{{ checklogs }} && make creates={{ nagtmp }}/{{ checklogs }}/plugins-scripts/check_logfiles

- name: make install Check logfiles plugin
  shell: cd  {{ nagtmp }}/{{ checklogs }} && make install creates=/usr/local/nagios/libexec/check_logfiles

- name: upload Nagios configuration
  copy:
      src=roles/nagios/files/conf/
      dest=/usr/local/nagios/etc/
      owner=nagios
      group=nagios 

- name: upload check_mem plugin
  copy:
      src=roles/nagios/files/check_mem
      dest=/usr/local/nagios/libexec/
      owner=nagios
      group=nagios
      mode=0755

- name: Add nrpe server to autostart
  shell: echo "/usr/local/nagios/bin/nrpe -c /usr/local/nagios/etc/nrpe.cfg -d" >> /etc/rc.local

- name: Start nrpe server
  shell: /usr/local/nagios/bin/nrpe -c /usr/local/nagios/etc/nrpe.cfg -d

- name: Ensure that Nagios service is started over init.d, so it can be used with systemctl afterwards
  shell: /etc/init.d/nagios start

- name: Ensure Nagios is started
  service: name=nagios state=started enabled=yes
